
name: ynpm
version: 0.5.2
description: npm wrapper allowing to use package.yaml instead of package.json

author:
  name: Alex Kocharin
  email: alex@kocharin.ru

keywords:
  - package manager
  - modules
  - install
  - package.yaml

preferGlobal: true
homepage: https://npmjs.org/doc/
 
repository:
  type: git
  url: https://github.com/rlidwka/ynpm

bugs:
  url: http://github.com/rlidwka/ynpm/issues

main: ./ynpm.js

bin:
  ynpm: ./ynpm.js

engines:
  # depends on stream updates, seriously won't work on 0.8.x
  node: '>= 0.9.4'

dependencies:
  npm: '*'
  js-yaml: '*'

devDependencies:
  async: '*'

optionalDependencies:
  yaml-update: '*'

