
name: yapm
version: 0.6.0
description: npm wrapper allowing to use package.yaml instead of package.json

author:
  name: Alex Kocharin
  email: alex@kocharin.ru

keywords:
  - package manager
  - modules
  - install
  - package.yaml

preferGlobal: true
homepage: https://npmjs.org/doc/
 
repository:
  type: git
  url: https://github.com/rlidwka/yapm

bugs:
  url: http://github.com/rlidwka/yapm/issues

main: ./yapm.js

bin:
  yapm: ./yapm.js

dependencies:
  npm: '*'
  js-yaml: '*'
  through: '*'

devDependencies:
  async: '*'

optionalDependencies:
  yaml-update: '*'

